version: '3.8'
services:  
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      
    ports:
      - "5432:5432"

  db_setup:
    container_name: db-setup
    build: 
      context: .
      dockerfile: db-setup/Dockerfile
    depends_on: 
      - db
    restart: "no"
    volumes:
      - ./db-setup:/var/db-setup
    links:
      - db  

  db_manager:
    container_name: db_manager
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

