version: '3.8'
services:  
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      
    ports:
      - "5432:5432"

  db_setup:
    container_name: db-setup
    image: node:alpine
    working_dir: /db_setup
    depends_on: 
      - db
    restart: "no"
    volumes:
      - .:/db_setup
    links:
      - db  
    command: /bin/sh -c "npm install && npm start"


